export const API_URL = "http://localhost:8080/api"
export const BASE_URL = "http://localhost:8080"
export const REGISTER_URL = "http://localhost:8080/user/register"
export const RESET_PASSWORD_URL = "http://localhost:8080/user/resetPassword"
export const SIGNIN_TOKEN = "dummy"
